name: network-docker
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    cap_add:
      - NET_RAW
      - NET_ADMIN
    cap_drop:
      - ALL
    container_name: client
    networks:
      lan: null
    volumes:
      # Workaround to prevent Docker Engine from setting the content of /etc/resolv.conf
      # NOTE: the IP address of the router is hardcoded in ./client/files/etc/resolv.conf
      # TODO: find a better way
      - type: bind
        source: ./client/files/etc/resolv.conf
        target: /etc/resolv.conf
        read_only: true
        bind:
          create_host_path: true
  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    container_name: router
    networks:
      lan: null
      wan: null
    # TODO: enable only the required capabilities
    privileged: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    cap_add:
      - NET_RAW
      - NET_ADMIN
    cap_drop:
      - ALL
    container_name: server
    networks:
      wan: null
networks:
  lan:
    name: network-docker_lan
    driver: bridge
    internal: true
  wan:
    name: network-docker_wan
    driver: bridge
    internal: true
