services:
  client:
    build:
      context: ./client  # Directory where the Dockerfile for the client is located
      dockerfile: Dockerfile  # Use the Dockerfile named Dockerfile
    container_name: client  # Name of the container instance
    networks:
      - lan  # Connect the client container to the 'lan' network
    cap_drop:
      - ALL  # Drop all capabilities by default for security
    cap_add:
      - NET_RAW  # Allow raw packet access (needed for ping)
      - NET_ADMIN  # Allow administrative network tasks (like configuring IP addresses)
    volumes:
      # Workaround to prevent Docker Engine from setting the content of /etc/resolv.conf
      # NOTE: the IP address of the router is hardcoded in ./client/files/etc/resolv.conf
      # TODO: find a better way
      - ./client/files/etc/resolv.conf:/etc/resolv.conf:ro

  router:
    build:
      context: ./router  # Directory where the Dockerfile for the router is located
      dockerfile: Dockerfile  # Use the Dockerfile named Dockerfile
    container_name: router  # Name of the container instance
    privileged: true  # Grant the container extended privileges for advanced networking (required for iptables)
    networks:
      - lan  # Connect the router to the 'lan' network
      - wan  # Connect the router to the 'wan' network
    cap_drop:
      - ALL  # Drop all capabilities by default for security
    cap_add:
      - NET_ADMIN  # Allow network administrative tasks like setting up routes and iptables
      - NET_RAW  # Allow raw socket access (required for advanced packet operations)
      - SYS_MODULE  # Allow loading/unloading of kernel modules (required for some network modules)

  server:
    build:
      context: ./server  # Directory where the Dockerfile for the server is located
      dockerfile: Dockerfile  # Use the Dockerfile named Dockerfile
    container_name: server  # Name of the container instance
    networks:
      - wan  # Connect the server container to the 'wan' network
    cap_drop:
      - ALL  # Drop all capabilities by default for security
    cap_add:
      - NET_RAW  # Allow raw packet access (needed for ping)
      - NET_ADMIN  # Allow administrative network tasks (like configuring IP addresses)

networks:
  lan:
    driver: bridge  # Use a bridge network for LAN to simulate a local network segment
    internal: true
  wan:
    driver: bridge  # Use a separate bridge network for WAN to simulate an external network segment
    internal: true
